pcm.softrec {
    type softvol
    slave.pcm "hw:rockchippdm,0"
    control.name "MicGain"
    control.card rockchippdm
    min_dB -10.0
    max_dB 30.0
    resolution 100
}
ctl.softrec {
    type hw
    card rockchippdm
}