SectionDevice."Mic" {
    Comment "PDM Microphone"

    Value {
        CapturePriority 100
        CapturePCM "hw:${CardId},0"
    }

    EnableSequence [
        cset "name='Receive PATH0 Source Select' 'From SDI1'"
    ]

    DisableSequence [
        cset "name='Receive PATH0 Source Select' 'From SDI0'"
    ]
}
